### ISSUE TITLE
com.github.peshay.download.MindManager - No match found

### ISSUE THREAD

**Issue by Daz-wallace** [autopkg/peshay-recipes#38]
```
The following recipes failed:
    com.github.peshay.download.MindManager
        Error in com.github.peshay.download.MindManager: Processor: URLTextSearcher: Error: No match found on URL: https://www.mindjet.com/support-info/download-library
```

Digging in now to see if I can file a PR

**Comment by Daz-wallace** [comment]
It looks like the dev reverted the change that needed this commit [c800f08](https://github.com/autopkg/peshay-recipes/commit/c800f0859e56f8e1a5766504769f2f92f7449bf7) but I'm struggling to revert and keep it valid and working.

Any hints? 😊

**Comment by rickheil** [comment]
Changing back should fix it. @Daz-wallace make sure you are escaping the < signs as below?
`<string>Build ([^"]*)\)[^&lt;]+&lt;a href=\"https://www.mindjet.com/mm-mac-dmg</string>`

**Comment by Daz-wallace** [comment]
Thanks @rickheil 
Looks like @roratonet Fixed it - https://github.com/autopkg/peshay-recipes/commit/52072c8fcfdb565e3a63d96eb87011e1f4f8f533

I've also added a pull for App Signature checking
