### ISSUE TITLE
Mattermost download recipe get RC

### ISSUE THREAD

**Issue by ygini** [autopkg/peshay-recipes#42]
Hello,

We are using your Mattermost download recipe and it currently download the RC version of Mattermost, which isn't expected (it's in beta in the Mattermost github release stream, not in stable).

Could you fix the recipe to use only the stable one by default?

Thanks a lot

**Comment by octomike** [comment]
same here, I think the recipe should make use of https://github.com/autopkg/autopkg/wiki/Processor-GitHubReleasesInfoProvider, no?

**Comment by roratonet** [comment]
Done!
Thank you 🙏
