### ISSUE TITLE
Platypus.download.recipe Returning a curl 60 error

### ISSUE THREAD

**Issue by Daz-wallace** [autopkg/peshay-recipes#45]
Getting a curl error on the download recipe.
Looks like the AppCast URL's HTTPS cert expired yesterday - https://sveinbjorn.org/files/appcasts/PlatypusAppcast.xml 

I'll see if I can reach out to the dev.

Email sent to the dev at sveinbjorn@sveinbjorn.org, let's see if it is resolved.

**Comment by roratonet** [comment]
@Daz-wallace 
Seems to be fixed.
Thank you for your support.
