### ISSUE TITLE
MindManager download recipe failing - URLTextSearcher

### ISSUE THREAD

**Issue by neilmartin83** [autopkg/peshay-recipes#46]
Hi,

It looks like the vendor has changed the download page - https://www.mindjet.com/support-info/download-library - so the URLTextSearcher isn't getting a result.

They have released a new major version of the app (13), so I wasn't sure whether to submit a PR for this recipe to get that (they have renamed the app as well), or if you wanted to keep this recipe downloading v12 and rename it appropriately.

If you'd like to keep this recipe for v12, please let me know and I can put together a new one for v13 on our repo.

Thanks!

**Comment by roratonet** [comment]
Hi,

thank you. I think we are good to go with v. 13 therefore I've changed the recipe for it.
Please let me know if this works for you.

Cheers,

**Comment by jc0b** [comment]
Seeing as this is still open: MindJet changed the download page again. I've addressed this in #48.

**Comment by roratonet** [comment]
Merged and closed
