### ISSUE TITLE
Zoom.filewave.recipe

### ISSUE THREAD

**Issue by jfuchtm** [autopkg/peshay-recipes#47]
Should this recipe be pulling the sub-updates? I am only seeing major version, not the last two updates.

**Comment by roratonet** [comment]
Hi,

in my case it's downloading:

The following fileset was imported:
    Fw Fileset Id  Fw Fileset Group  Fw Fileset Name
    -------------  ----------------  ---------------
    38618635       02NewAdded        Zoom - 5.0.24978.0517

Which corresponds to the version in https://zoom.us/download#client_4meeting

Version 5.0.3 (24978.0517)

Even the installed software is correct.
It seems that the %version% variable, which the recipe is pulling, is made by the major 5.0 plus the build number 24978.0517.

All ok in my eyes, until the latest version is downloaded.

**Comment by roratonet** [comment]
No updates so far - closing the case
