### ISSUE TITLE
Mattermost architecture changes

### ISSUE THREAD

**Issue by grahampugh** [autopkg/peshay-recipes#61]
Hi, the default architecture filter for Mattermost in Mattermost.download is currently `mac`, but this is no longer one of the options, so the latest version (5.0.1) is not getting picked up. I would recommend that the default is changed to `mac-universal`. 

I have verified that the recipe gets the latest universal DMG when `--key os=mac-universal` is supplied.

**Comment by roratonet** [comment]
Hi,

thank you!
I've changed the default to `mac-universal` and added `mac-arm64`
